<RootWidget>:
    orientation: 'vertical'

    ScreenManager:
        size_hint: 1, .9
        id: _screen_manager
        Screen:
            name: 'screen1'
            BoxLayout:
                orientation: 'vertical'
                BoxLayout:
                    size_hint: 1, 0.3
                    Label:
                        text: root.A[0]
                        font_size: 20
                BoxLayout:
                    size_hint: 1, 0.5
                    orientation: 'horizontal'
                    BoxLayout:
                        padding: 50
                        orientation: 'vertical'
                        CheckBox:
                            
                            id: 'Option1'
                            group: 'group1'
                            size_hint: None, None
                            pos_hint_x: 0.5
                            
                        CheckBox:
                            
                            id: 'Option2'
                            group: 'group1'
                            size_hint: None, None
                            
                        CheckBox:
                            
                            id: 'Option3'
                            group: 'group1'
                            size_hint: None, None
                            
                        
                    BoxLayout:
                        padding: 50
                        orientation: 'vertical'
                        Label:
                            halign: 'left'
                            text_size: self.size
                            id: 'Label1'
                            size_hint: None,None
                            text: root.A[1]
                            font_size: 20
                        Label:
                            halign: 'left'
                            text_size: self.size
                            id: 'Label2'
                            size_hint: None,None
                            text: root.A[2]
                            font_size: 20
                        Label:
                            halign: 'left'
                            text_size: self.size
                            id: 'Label3'
                            size_hint: None,None
                            text: root.A[3]
                            font_size: 20
        Screen:
            name: 'screen2'
            BoxLayout:
                orientation: 'vertical'
                BoxLayout:
                    size_hint: 1, 0.3
                    Label:
                        text: root.A[4]
                        font_size: 20
                BoxLayout:
                    size_hint: 1, 0.5
                    orientation: 'horizontal'
                    BoxLayout:
                        padding: 50
                        orientation: 'vertical'
                        CheckBox:
                            
                            id: 'Option1'
                            group: 'group1'
                            size_hint: None, None
                            pos_hint_x: 0.5
                            
                        CheckBox:
                            
                            id: 'Option2'
                            group: 'group1'
                            size_hint: None, None
                            
                        CheckBox:
                            
                            id: 'Option3'
                            group: 'group1'
                            size_hint: None, None
                            
                        
                    BoxLayout:
                        padding: 50
                        orientation: 'vertical'
                        Label:
                            halign: 'left'
                            text_size: self.size
                            id: 'Label1'
                            size_hint: None,None
                            text: root.A[5]
                            font_size: 20
                        Label:
                            halign: 'left'
                            text_size: self.size
                            id: 'Label2'
                            size_hint: None,None
                            text: root.A[6]
                            font_size: 20
                        Label:
                            halign: 'left'
                            text_size: self.size
                            id: 'Label3'
                            size_hint: None,None
                            text: root.A[7]
                            font_size: 20       
    BoxLayout:
        padding: 15
        orientation: 'horizontal'
        size_hint: 1, .1
        Button:
            text: 'Submit'
            #on_press: root.Submit()
        Button:
            text: 'Go to Screen 2'
            on_press: _screen_manager.current = 'screen2'            
            
                    
         #   BoxLayout:
         #       padding: 15
         #       orientation: 'horizontal'
          #      size_hint: 1, .1
          #      Button:
          #          text: 'Submit'
                    
          #      Button:
          #          text: 'Go to Screen 2'
          #          on_press: _screen_manager.current = 'screen2'   
